table Data_vol
	lineageTag: 51ca5fe5-e296-47f6-b8af-fdb56abe7388

	measure Pcio_Lt = sum('Data_vol'[VentaValorizada])/sum(Data_vol[Volumen_Lts])
		lineageTag: 0edd1a16-5b59-4f06-8a9e-a561685b434d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pcio_Uni = sum('Data_vol'[VentaValorizada])/sum(Data_vol[Unidades])
		lineageTag: 87fdb01f-9a49-4a01-af5e-7aafaf9c1557

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Suma de Volumen_Lts' = SUM('Data_vol'[Volumen_Lts])
		lineageTag: d20652c8-b684-4b66-be18-4f7c389294ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Suma de VentaValorizada' = SUM('Data_vol'[VentaValorizada])
		lineageTag: 3b78ed33-036d-4b09-a01c-a324641b0e86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Suma de Unidades' = SUM('Data_vol'[Unidades])
		lineageTag: 2972d277-31bd-499c-a6af-3dd30f0cb33f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Source.Name'
		dataType: string
		isHidden
		lineageTag: 43e4c1b2-cee3-47f7-a671-321a1ec888a4
		sourceColumn: Source.Name

		annotation PBI_FormatHint = {"isText":true}

	column SEMANA
		dataType: int64
		lineageTag: e9098e37-d681-4bc7-ad1d-cf8aa4392095
		sourceColumn: SEMANA

	column MES
		dataType: int64
		lineageTag: d8cf7406-103f-4aa9-b1e5-8efe65344b4e
		sourceColumn: MES

	column AÑO
		dataType: int64
		lineageTag: 5cc8bba5-9df6-4a9c-bc78-5f7d5465fc2b
		sourceColumn: AÑO

	column BANDERA
		dataType: string
		lineageTag: 383dc586-5fcf-4861-8b6b-e5ab8589ff79
		sourceColumn: BANDERA

	column GRUPO
		dataType: string
		lineageTag: 08741ee6-bb43-41e4-bd7f-d78b5431f818
		sourceColumn: GRUPO

	column CATEGORIA
		dataType: string
		isHidden
		lineageTag: 600ab766-9af6-46e3-8c30-d60e39222408
		sourceColumn: CATEGORIA

	column AREA_CCU
		dataType: string
		lineageTag: d3b18342-a10c-4702-862d-7e835a270c43
		sourceColumn: AREA_CCU

	column GranArea_CCU
		dataType: string
		lineageTag: ffdc1909-26d8-4efa-b004-fe2bc8cc2623
		sourceColumn: GranArea_CCU

	column SUBAREA_CCU
		dataType: string
		lineageTag: 57d6ab6d-a2b5-4f81-8a19-bab16160823b
		sourceColumn: SUBAREA_CCU

	column Formato_M2
		dataType: string
		lineageTag: c68cff31-ad39-48f5-8891-eef0ad52a4cc
		sourceColumn: Formato_M2

	column EAN
		dataType: int64
		isHidden
		lineageTag: eb004a9a-ce2c-485a-ab74-55f0b1f536c4
		sourceColumn: EAN

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EAN_DESC
		dataType: string
		isHidden
		lineageTag: 5a110314-6efb-4dc8-ac98-24b848bf3e68
		sourceColumn: EAN_DESC

	column CALIBRE
		dataType: int64
		isHidden
		lineageTag: 2b7e17eb-2f75-4048-b651-98f5b27ad18d
		sourceColumn: CALIBRE

	column CONTENIDO
		dataType: int64
		isHidden
		lineageTag: af545cba-1ca2-4b54-aa5b-334269840a74
		sourceColumn: CONTENIDO

	column Unidades
		dataType: int64
		lineageTag: 0be264b3-1865-43ef-8073-32aab08241f9
		sourceColumn: Unidades

	column VentaValorizada
		dataType: double
		lineageTag: f0257148-be5a-45e2-a6ae-30bd98cb421b
		sourceColumn: VentaValorizada

	column Volumen_Lts
		dataType: double
		lineageTag: 29bfaac7-1eae-49c3-a41b-8abcb4f56005
		sourceColumn: Volumen_Lts

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'pcio por uni'
		dataType: string
		isHidden
		lineageTag: 8cc34d9e-80e4-4f7b-b5f6-ba8d93af3d1b
		sourceColumn: pcio por uni

	column 'Pciox vol'
		dataType: double
		isHidden
		lineageTag: c55b7d8e-2dc9-479e-b122-a50446492766
		sourceColumn: Pciox vol

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Data_vol = m
		source =
				let
				    Origen = Folder.Files("C:\CLIENTES\Semanal\5_CONSOLIDADOS\CERVEZAS\Data_vol_CCU"),
				    #"Archivos ocultos filtrados1" = Table.SelectRows(Origen, each [Attributes]?[Hidden]? <> true),
				    #"Invocar función personalizada1" = Table.AddColumn(#"Archivos ocultos filtrados1", "Transformar archivo", each #"Transformar archivo"([Content])),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Invocar función personalizada1", {"Name", "Source.Name"}),
				    #"Otras columnas quitadas1" = Table.SelectColumns(#"Columnas con nombre cambiado1", {"Source.Name", "Transformar archivo"}),
				    #"Columna de tabla expandida1" = Table.ExpandTableColumn(#"Otras columnas quitadas1", "Transformar archivo", Table.ColumnNames(#"Transformar archivo"(#"Archivo de ejemplo"))),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna de tabla expandida1",{{"Source.Name", type text}, {"Sem hasta", type date}, {"Semana Scentia", Int64.Type}, {"Mes Scentia", Int64.Type}, {"Año Scentia", Int64.Type}, {"Cadena CCU", type text}, {"Categoria", type text}, {"Area Inbev", type any}, {"Zona Inbev", type any}, {"Area_RS_CCU", type text}, {"Gran Area KA CCU", type text}, {"Area KA CCU", type text}, {"Formato M2 2", type any}, {"Formato M2", type text}, {"EAN", Int64.Type}, {"EAN DESC", type text}, {"Peso Volumen", Int64.Type}, {"Contenido", Int64.Type}, {"CANTIDAD", Int64.Type}, {"Venta Valorizada", type number}, {"Volumen_Lts", type number}, {"Pciox vol", type number}, {"Cadena", type any}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Sem hasta"}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas quitadas",{"Area Inbev", "Zona Inbev", "Formato M2 2", "Cadena"}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Columnas quitadas1", "Grupo", each if [Cadena CCU] = "JUMBO" then "CENCOSUD" else if [Cadena CCU] = "DISCO" then "CENCOSUD" else if [Cadena CCU] = "VEA" then "CENCOSUD" else if [Cadena CCU] = "SPID35" then "CENCOSUD" else if [Cadena CCU] = "WALMART - CHANGOMAS" then "GDN" else if [Cadena CCU] = "DIA" then "DIA" else if [Cadena CCU] = "COOP. OBRERA" then "COOP. OBRERA" else if [Cadena CCU] = "TOLEDO" then "TOLEDO" else [Cadena CCU]),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columna condicional agregada",{"Source.Name", "Semana Scentia", "Mes Scentia", "Año Scentia", "Cadena CCU", "Grupo", "Categoria", "Area_RS_CCU", "Gran Area KA CCU", "Area KA CCU", "Formato M2", "EAN", "EAN DESC", "Peso Volumen", "Contenido", "CANTIDAD", "Venta Valorizada", "Volumen_Lts", "Pciox vol"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas reordenadas", each true),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas1",{{"Cadena CCU", "BANDERA"}, {"Grupo", "GRUPO"}, {"Categoria", "CATEGORIA"}, {"Area_RS_CCU", "AREA_CCU"}, {"Gran Area KA CCU", "GranArea_CCU"}, {"Area KA CCU", "SUBAREA_CCU"}, {"Formato M2", "Formato_M2"}, {"EAN DESC", "EAN_DESC"}, {"Peso Volumen", "CALIBRE"}, {"Contenido", "CONTENIDO"}, {"CANTIDAD", "Unidades"}, {"Venta Valorizada", "VentaValorizada"}, {"Año Scentia", "AÑO"}, {"Mes Scentia", "MES"}, {"Semana Scentia", "SEMANA"}}),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Columnas con nombre cambiado",{"DROP"}),
				    #"Consulta anexada" = Table.Combine({#"Columnas quitadas2", #"Data_vol Unificado"}),
				    #"Filas filtradas" = Table.SelectRows(#"Consulta anexada", each ([AÑO] <> 2023))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

