table IM
	lineageTag: 9fa5f679-1edc-424c-977e-52c70f8ba5cb

	column EAN_TEXTO
		dataType: string
		lineageTag: dfc13279-b32c-42b3-af21-72cf893ff954
		summarizeBy: none
		sourceColumn: EAN_TEXTO

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column EAN
		dataType: double
		isHidden
		lineageTag: 21bfa668-8486-48e2-a09d-a6f3b1f9e2e2
		summarizeBy: none
		sourceColumn: EAN

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = Automatic

	column EAN_DESC
		dataType: string
		lineageTag: e57b9a8e-4500-4ca7-a91f-9135990eddc8
		summarizeBy: none
		sourceColumn: EAN_DESC

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 4eb8ed9c-4f4b-459b-b230-0af063e8684c
		summarizeBy: none
		sourceColumn: Categoria

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column Calibre
		dataType: double
		lineageTag: d972f9fe-0b44-46de-b80c-c245046dd8f2
		summarizeBy: sum
		sourceColumn: Calibre

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = Automatic

	column Contenido
		dataType: double
		lineageTag: a95f6471-8b7b-4d3c-87e3-241acc210f18
		summarizeBy: sum
		sourceColumn: Contenido

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = Automatic

	column SIZE_CCU
		dataType: string
		lineageTag: be633614-3896-4ec0-a9f4-314a5dcab8cd
		summarizeBy: none
		sourceColumn: SIZE_CCU

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column MANUF
		dataType: string
		lineageTag: 7bea503f-3bc3-47ea-a32b-8042849ecc29
		summarizeBy: none
		sourceColumn: MANUF

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column BRAND
		dataType: string
		lineageTag: 62c78f2e-738d-44b6-8180-035e86e7558b
		summarizeBy: none
		sourceColumn: BRAND

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column ENVASE
		dataType: string
		lineageTag: 6dc85b0a-5402-4407-a724-8f21f147b871
		summarizeBy: none
		sourceColumn: ENVASE

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column SEGMENTO
		dataType: string
		lineageTag: 1543b722-1081-44bd-911e-ec2831013f34
		summarizeBy: none
		sourceColumn: SEGMENTO

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column SUBBRAND
		dataType: string
		lineageTag: fe83495c-93e0-4a68-99c9-3b1ae66f97d5
		summarizeBy: none
		sourceColumn: SUBBRAND

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column COLOR
		dataType: string
		isHidden
		lineageTag: c3d5ef54-3a7c-474d-89b5-55e34a883436
		summarizeBy: none
		sourceColumn: COLOR

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column RET_NORET
		dataType: string
		lineageTag: fa1225b0-3a63-4ef7-a827-41b240da2019
		summarizeBy: none
		sourceColumn: RET_NORET

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column SEG_LIQUIDO
		dataType: string
		lineageTag: 111d23b1-3ebb-432a-add0-6caf84c856de
		summarizeBy: none
		sourceColumn: SEG_LIQUIDO

		annotation PBI_FormatHint = {"isText":true}

		annotation SummarizationSetBy = Automatic

	column 'Manuf 2'
		dataType: string
		lineageTag: 7bed4831-cbdb-458c-b064-8a746a2cbe4e
		summarizeBy: none
		sourceColumn: Manuf

		annotation SummarizationSetBy = Automatic

	column 'Brand 2'
		dataType: string
		lineageTag: b886383b-f471-4879-ac92-84606fe7257e
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column 'Envase 2'
		dataType: string
		lineageTag: 0536cae6-84df-4404-95ee-00585f4a68a7
		summarizeBy: none
		sourceColumn: Envase

		annotation SummarizationSetBy = Automatic

	column CLAS_INBEV
		dataType: string
		lineageTag: ff74493b-fa9b-49ac-ae0b-cc5e42168694
		summarizeBy: none
		sourceColumn: CLAS_INBEV

		annotation SummarizationSetBy = Automatic

	column SUBBRAND_INBEV
		dataType: string
		lineageTag: e4c518d4-bf5d-404a-9f66-2fa732d17bb2
		summarizeBy: none
		sourceColumn: SUBBRAND_INBEV

		annotation SummarizationSetBy = Automatic

	column DESC_2
		dataType: string
		lineageTag: fa6e6e9e-1c8a-4f4e-b4b6-26c3f291563d
		summarizeBy: none
		sourceColumn: DESC_2

		annotation SummarizationSetBy = Automatic

	column TIPO_ENV
		dataType: string
		lineageTag: 48ed35fb-2e09-4ad0-80a3-88336446c8f2
		summarizeBy: none
		sourceColumn: TIPO_ENV

		annotation SummarizationSetBy = Automatic

	column SIZE
		dataType: string
		lineageTag: c4dc9cc3-e3fa-406d-bfdb-5ba56a03f70a
		summarizeBy: none
		sourceColumn: SIZE

		annotation SummarizationSetBy = Automatic

	column ALCOHOL
		dataType: string
		lineageTag: eb661a90-a287-44d5-8cbb-31db8f9e8bd2
		summarizeBy: none
		sourceColumn: ALCOHOL

		annotation SummarizationSetBy = Automatic

	partition IM = m
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Dario Sidi\Downloads\wetransfer_data_vol-zip_2025-11-11_1209\IM.xlsx"), null, true),
				    Sheet = Source{[Item="IM",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers", {{"EAN_TEXTO", "EAN_TEXTO"}, {"EAN", "EAN"}, {"EAN_DESC", "EAN_DESC"}, {"Categoria", "Categoria"}, {"Calibre", "Calibre"}, {"Contenido", "Contenido"}, {"MANUF_CCU", "MANUF"}, {"BRAND_CCU", "BRAND"}, {"ENV_CCU", "ENVASE"}, {"CLASIF_CCU", "SEGMENTO"}, {"SUBBRAND_CCU", "SUBBRAND"}, {"COLOR_CCU", "COLOR"}, {"RET_NORET", "RET_NORET"}, {"SEG_LIQUIDO", "SEG_LIQUIDO"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"EAN_TEXTO", type text}, {"EAN", type number}, {"EAN_DESC", type text}, {"Categoria", type text}, {"Calibre", type number}, {"Contenido", type number}, {"SIZE", type text}, {"MANUF", type text}, {"BRAND", type text}, {"ENVASE", type text}, {"SEGMENTO", type text}, {"SUBBRAND", type text}, {"COLOR", type text}, {"RET_NORET", type text}, {"SEG_LIQUIDO", type text}})
				 in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

