table Medida
	lineageTag: 31c25e91-5143-4213-ace2-e4f4022e15d6

	measure '% Share Volumen' =
			DIVIDE(
			    SUM(Data_vol[Volumen_Lts]),
			    CALCULATE(
			        SUM(Data_vol[Volumen_Lts]),
			        ALL(IM[MANUF], IM[EAN_DESC], IM[BRAND], IM[MANUF 2])
			    )
			)
		lineageTag: c59ec888-147d-42b5-8439-0c7916ac9ed8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volumen Semana Anterior' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			VAR SemanaAnterior = SemanaActual - 1
			RETURN 
			CALCULATE(SUM(Data_vol[Volumen_Lts] ),Calendario[Ano-Sem_NUM]=SemanaAnterior
			)
			
			
			```
		lineageTag: df1fff0c-c0d0-486a-bbfa-f6ff65650aca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Var_una_semana = ```
			
			 DIVIDE([Suma de Volumen_Lts]-[Volumen Semana Anterior],[Volumen Semana Anterior],0)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 84672915-05c3-4d87-ba21-d1ac212d39e5

	measure 'Var Semana Anterior' =
			
			VAR menor=[%Var_una_semana]<=-0.01
			VAR mayor=[%Var_una_semana]>=0.01
			RETURN IF(menor,"Rojo",IF(mayor,"Verde","Amarillo"))
		lineageTag: 6f09401b-c948-40f0-863b-08f84fddeb8a

	measure 'AVG Tres Semanas Anterior' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			RETURN
			CALCULATE(
			    AVERAGEX(
			        VALUES(Calendario[Ano-Sem_NUM]),
			        [Volumen_lts]
			    ),
			    FILTER(
			        ALL(Calendario),
			        Calendario[Ano-Sem_NUM] < SemanaActual &&
			        Calendario[Ano-Sem_NUM] >= SemanaActual - 3
			    )
			)
			
			
			
			
			
			
			
			
			
			
			```
		lineageTag: ab3b2f31-f55f-4302-b1a8-a62b162b3834

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Media_una_semana = ```
			
			 DIVIDE([Suma de Volumen_Lts]-[Volumen Semana Anterior],[Volumen Semana Anterior],0)
			```
		lineageTag: 137e3741-3fd8-41d8-9800-bf1ca6df0b31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Volumen_lts = SUM (Data_vol[Volumen_Lts])
		lineageTag: 49f390d9-b990-4ecb-a2b8-8f573440d5ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Tres Semanas' = ```
			
			VAR menor = DIVIDE([Volumen_lts]-[AVG Tres Semanas Anterior],[AVG Tres Semanas Anterior],0)<=-0.01
			VAR mayor = DIVIDE([Volumen_lts]-[AVG Tres Semanas Anterior],[AVG Tres Semanas Anterior],0)>=0.01
			RETURN IF(menor,"Rojo",IF(mayor,"Verde","Amarillo"))
			
			
			```
		lineageTag: f25f5f95-439f-4832-afd9-609bd7964722

	measure 'AVG Doce Semanas Anterior' =
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			RETURN
			CALCULATE(
			    AVERAGEX(
			        VALUES(Calendario[Ano-Sem_NUM]),
			        [Volumen_lts]
			    ),
			    FILTER(
			        ALL(Calendario),
			        Calendario[Ano-Sem_NUM] < SemanaActual &&
			        Calendario[Ano-Sem_NUM] >= SemanaActual - 12
			    )
			)
		lineageTag: 68329f4a-3748-4f09-ac01-987c4b7c8c0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Doce Semanas' =
			
			VAR menor = DIVIDE([Volumen_lts]-[AVG Doce Semanas Anterior],[AVG Doce Semanas Anterior],0)<=-0.01
			VAR mayor = DIVIDE([Volumen_lts]-[AVG Doce Semanas Anterior],[AVG Doce Semanas Anterior],0)>=0.01
			RETURN IF(menor,"Rojo",IF(mayor,"Verde","Amarillo"))
		lineageTag: 6943d3fb-9df5-474e-bfdc-6ca19b891282

	measure 'Indicador Rojos' = [Var Doce Semanas Num]+[Var Tres Semanas Num]+[Var Semana Anterior Num]+[Var Tendencia Estimada Num]+[Var Target Num]
		formatString: 0
		lineageTag: 89e1e3f3-5159-4150-a777-fdf55d008744

	measure Medida =
			
			DIVIDE([Volumen_lts]-[AVG Doce Semanas Anterior],[AVG Doce Semanas Anterior],0)
		lineageTag: f0657fc0-aedd-4bf8-b9f5-d10a68a112cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Semana Anterior Num' =
			
			VAR menor=[%Var_una_semana]<=-0.01
			RETURN IF(menor,1,0)
		formatString: 0
		lineageTag: 96911cf1-710d-4733-b4b6-17bee4e1d826

	measure 'Var Tres Semanas Num' =
			
			VAR menor = DIVIDE([Volumen_lts]-[AVG Tres Semanas Anterior],[AVG Tres Semanas Anterior],0)<=-0.01
			RETURN IF(menor,1,0)
		formatString: 0
		lineageTag: 6787ca0d-a577-4f69-8600-24188f4d0162

	measure 'Var Doce Semanas Num' =
			
			VAR menor = DIVIDE([Volumen_lts]-[AVG Doce Semanas Anterior],[AVG Doce Semanas Anterior],0)<=-0.01
			RETURN IF(menor,1,0)
		formatString: 0
		lineageTag: bd1453ff-35de-4db4-8a2e-222df1794310

	measure 'Volumen Tendencia Estimada' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			VAR SemanaAnterior = SemanaActual - 100
			RETURN 
			CALCULATE(SUM(Data_vol[Volumen_Lts] ),Calendario[Ano-Sem_NUM]=SemanaAnterior
			)
			
			```
		lineageTag: 9d569eb3-1358-42df-998e-357fc5e0c5b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '%Var MismaSemanaAnoAnterior' =
			
			DIVIDE([Volumen_Lts]-[Volumen Tendencia Estimada],[Volumen Tendencia Estimada],0)
		formatString: 0.00
		lineageTag: 9a2a7299-7914-47d6-aa39-4e2f277a9469

	measure 'Var Tendencia Estimada' =
			
			VAR menor=[Diferencia_vs_Real]<-10000
			VAR mayor=[Diferencia_vs_Real]>=10000
			RETURN IF(menor,"Rojo",IF(mayor,"Verde","Amarillo"))
		lineageTag: 03376104-b7fb-4d8a-8d94-0bc80bdba261

	measure 'Var Tendencia Estimada Num' =
			
			VAR menor=[Diferencia_vs_Real]<-10000
			RETURN IF(menor,1,0)
		formatString: 0
		lineageTag: 96492a05-e78b-4fb3-acbc-77d3c1de2312

	measure Target_Cliente = ```
			
			VAR _blank=ISBLANK (SELECTEDVALUE(Target[TARGET]))
			RETURN
			IF(SELECTEDVALUE(Target[TARGET])=BLANK(),[Volumen Tendencia Estimada],SELECTEDVALUE(Target[TARGET]))
			
			
			
			
			
			
			
			
			```
		formatString: 0
		lineageTag: 8a5eee0e-afea-4053-a543-7b0f1dbeb9c5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Var Target' = ```
			
			
			VAR menor = [Volumen_lts]<[Target_Cliente]  *0.85
			VAR mayor = [Volumen_lts]>=[Target_Cliente]  
			RETURN IF(menor,"Rojo",IF(mayor,"Verde","Amarillo"))
			```
		lineageTag: c0528bd2-9673-499b-867a-be06bf54f0e7

	measure 'Var Target Num' = ```
			
			
			VAR menor = [Volumen_lts]<[Target_Cliente]  *0.85
			VAR mayor = [Volumen_lts]>=[Target_Cliente]  
			RETURN IF(menor,1,0)
			```
		formatString: 0
		lineageTag: caf085d2-91a3-4881-8fbb-d4e7010b6762

	measure 'Volumen Semana Anterior P_Vol' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			VAR SemanaAnterior = SemanaActual - 1
			RETURN 
			CALCULATE(SUM(Data_vol[Pciox vol] ),Calendario[Ano-Sem_NUM]=SemanaAnterior
			)
			```
		lineageTag: 1a15df81-83a4-4f35-9c96-c24203b4311d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PPL Doce Semanas' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			RETURN
			CALCULATE(
			    [Pcio_Lt],
			    FILTER(
			        ALL(Calendario),
			        Calendario[Ano-Sem_NUM] < SemanaActual &&
			        Calendario[Ano-Sem_NUM] >= SemanaActual - 12
			    )
			)
			
			
			
			```
		formatString: 0.00
		lineageTag: 30d62e10-63fd-40d0-abcb-2288eb0393b6

	measure 'Var PLL Doce Semanas' =
			
			VAR valor = DIVIDE([Pcio_Lt]-[PPL Doce Semanas],[PPL Doce Semanas],0)
			RETURN valor
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 82dfc579-0824-4073-b3d9-c84411b199f5

	measure 'Aporte Vol Grupo' = DIVIDE([Volumen_lts],CALCULATE([Volumen_lts],ALL(Data_vol[GRUPO])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 2e6ec932-6ccc-4915-b68c-da6ee77fb6ce

	measure Diferencia_vs_Real =
			
			[Volumen_LTS] - [Tendencia_Estimada]
		lineageTag: ddfab2b8-f87a-42e2-b6f3-489deffcf380

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pendiente_b =
			
			VAR Tabla =
			    ADDCOLUMNS(
			        ALLSELECTED(Calendario[Ano-Sem_NUM]),
			        "@x", Calendario[Ano-Sem_NUM],
			        "@y", [Volumen_LTS]    -- o tu medida de Share
			    )
			VAR XProm =
			    AVERAGEX(Tabla, [@x])
			VAR YProm =
			    AVERAGEX(Tabla, [@y])
			VAR Numerador =
			    SUMX(Tabla, ([@x] - XProm) * ([@y] - YProm))
			VAR Denominador =
			    SUMX(Tabla, ([@x] - XProm) ^ 2)
			RETURN
			    DIVIDE(Numerador, Denominador)
		lineageTag: 73825088-f114-41fa-97e8-97c9079788ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Interseccion_a = ```
			
			VAR b = [Pendiente_b]
			VAR Tabla =
			    ADDCOLUMNS(
			        ALLSELECTED(Calendario[Ano-Sem_NUM]),
			        "@x", Calendario[Ano-Sem_NUM],
			        "@y", [Volumen_LTS]
			    )
			VAR XProm =
			    AVERAGEX(Tabla, [@x])
			VAR YProm =
			    AVERAGEX(Tabla, [@y])
			RETURN
			    YProm - b * XProm
			
			```
		lineageTag: 45032fc9-224a-483e-a565-7b8fe3b5256c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tendencia_Estimada =
			
			VAR x_t = MAX(Calendario[Ano-Sem_NUM])  -- semana actual del contexto
			VAR a = [Interseccion_a]
			VAR b = [Pendiente_b]
			RETURN
			    a + b * x_t
		lineageTag: ee40b618-5124-4b9b-87be-cfea82a34de8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medida = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

