table Medida
	lineageTag: 31c25e91-5143-4213-ace2-e4f4022e15d6

	measure '% Share Volumen' =
			DIVIDE(
			    SUM(Data_vol[Volumen_Lts]),
			    CALCULATE(
			        SUM(Data_vol[Volumen_Lts]),
			        ALL(IM[MANUF], IM[EAN_DESC], IM[BRAND], IM[MANUF 2])
			    )
			)
		lineageTag: c59ec888-147d-42b5-8439-0c7916ac9ed8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volumen Semana Anterior' = ```
			
			VAR SemanaActual = MAX(Calendario[Ano-Sem_NUM])
			VAR SemanaAnterior = SemanaActual - 1
			RETURN 
			CALCULATE(SUM(Data_vol[Volumen_Lts] ),Calendario[Ano-Sem_NUM]=SemanaAnterior
			)
			
			
			```
		lineageTag: df1fff0c-c0d0-486a-bbfa-f6ff65650aca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure %Var_una_semana = ```
			
			 DIVIDE([Suma de Volumen_Lts]-[Volumen Semana Anterior],[Volumen Semana Anterior],0)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 84672915-05c3-4d87-ba21-d1ac212d39e5

	measure Parametro_num =
			
			VAR variacion=[%Var_una_semana]<0.5
			
			RETURN IF(variacion,1,0)
		formatString: 0
		lineageTag: 6f09401b-c948-40f0-863b-08f84fddeb8a

	partition Medida = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

