table Medida
	lineageTag: 31c25e91-5143-4213-ace2-e4f4022e15d6

	measure '% Share Volumen' =
			DIVIDE(
			    SUM(Data_vol[Volumen_Lts]),
			    CALCULATE(
			        SUM(Data_vol[Volumen_Lts]),
			        ALL(IM[MANUF], IM[EAN_DESC], IM[BRAND], IM[MANUF 2])
			    )
			)
		lineageTag: c59ec888-147d-42b5-8439-0c7916ac9ed8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Max_Fecha = MAX(Data_vol[Fecha_Combinada])
		lineageTag: e7ae5c03-41de-43e6-959d-e7f6245ef170

	partition Medida = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

