table Parametros_semaforo
	lineageTag: a86d6feb-a33f-402d-9259-cf0ea7be3d26

	column Color
		dataType: string
		lineageTag: 040339ed-3826-472f-9e16-7ec6b2f5c12d
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: int64
		formatString: 0
		lineageTag: 2dac0514-8fc0-4cb3-b538-860b71f63d44
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	partition Parametros_semaforo = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCsrPylfSUTLQM1WK1YlWCkstSkkF8y2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t, Columna2 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}, {"Columna2", Int64.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Columna1", "Color"}, {"Columna2", "Valor"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

